name: Draft PDF Joss paper
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        id: build
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
          args: "-o pdf --verbose --dump-args"

      - name: Copy LaTeX temp directory
        run: |
          mkdir -p latex-debug
          cp -r /tmp/tex2pdf* latex-debug || true

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf

      - name: Upload LaTeX sources
        uses: actions/upload-artifact@v4
        with:
          name: latex-debug
          path: latex-debug
