name: Build JOSS PDF

on:
  push:
    paths:
      - paper.md
      - paper/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Inara to build PDF
        uses: docker://openjournals/inara:latest
        with:
          args: -o pdf paper/paper.md

